# TBA: For now just true

deployment:
  affinity: {}
  nodeSelector: {}
  tolerations: []

  serviceAccount:
    annotations: {}

  gateway:
    enable: true
    AWSLoadBalancerController: true
    domain: ""

  containers:
    virtualKubelet:
      image:
        repository: "public.ecr.aws/m4v1f8q5/gpu-provider/virtual-kubelet"
        tag: latest
        pullPolicy: Always

      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"

    gateway:
      image:
        repository: "public.ecr.aws/m4v1f8q5/gpu-provider/gateway"
        tag: latest
        pullPolicy: Always

      resources:
        requests:
          cpu: "0.5"
          memory: "512Mi"
        limits:
          cpu: "0.5"
          memory: "512Mi"


# Application configuration
appConfig:
  logLevel: "info"

  cluster:
    clusterUUID: ""

  cloudProvider:
    vastAI:
      apiKey: ""

  virtualNode:
    nodeName: "virtual-node"
    podLimit: "10"
    cpu: "1000"
    memory: "1000Gi"
    labels: {}
    taints: []

  provisioning:
    maxRetries: 10
    startupTimeout: "10m"
    statusReportTimeout: "2m"
    machineBansStore:
      localFile:
        enable: true
        timeout: "1d"

  gateway:
    configPath: /gateway/config.yaml

  promtail:
    enable: false
    clients: []
