# Pod limit configuration
podLimit: 20

deployment:
  affinity: {}
  nodeSelector: {}

  serviceAccount:
    annotations: {}

  containers:
    virtualKubelet:
      image:
        repository: "391135486350.dkr.ecr.eu-central-1.amazonaws.com/gpu-provider"
        tag: latest
        pullPolicy: Always

      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"

  gateway:
    enable: true
    AWSLoadBalancerController: false
    domain: ""
    port: 51820
    nodePort: 31311

    image:
      repository: "391135486350.dkr.ecr.eu-central-1.amazonaws.com/gpu-provider"
      tag: "gateway"
      pullPolicy: Always

    resources:
      requests:
        cpu: "0.5"
        memory: "512Mi"
      limits:
        cpu: "0.5"
        memory: "512Mi"


# Application configuration
appConfig:
  logLevel: "info"

  cluster:
    clusterUUID: ""

  cloudProvider:
    vastAI:
      apiKey: ""

  virtualNode:
    nodeName: "virtual-node"
    podLimit: "1"
    cpu: "1000"
    memory: "1000Gi"
    labels: {}
    taints: []

  provisioning:
    maxRetries: 10
    startupTimeout: "10m"
    statusReportTimeout: "2m"
    machineBansStore:
      localFile:
        enable: true
        timeout: "1d"

  agentAuthToken: ""

  proxy:
    enable: false

  promtail:
    enable: false
    clients: []
