cluster:
  clusterUUID: ""

cloudProvider:
  vastAI:
    apiKey: ""

virtualKubelet:
  image:
    repository: "391135486350.dkr.ecr.eu-central-1.amazonaws.com/gpu-provider"
    pullPolicy: Always

  serviceAccount:
    annotations: {}

  provisioning:
    maxRetries: 10
    startupTimeout: "10m"
    machineBansStore:
      localFile:
        enable: true
        timeout: "1d"

virtualNode:
  pods: "1"
  cpu: "1000"
  memory: "1000Gi"

agentAuthToken: ""

proxy:
  enable: false

promtail:
  enable: false
  clients: []
    # - url: "https://example-loki-gateway.com/loki/api/v1/push"
    #   basicAuth:
    #     username: "username"
    #     password: "password"
