apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-proxy
  template:
    metadata:
      labels:
        app: wireguard-proxy
    spec:
      nodeSelector:
        wg/node: "true"
      tolerations:
        - key: "wg/only"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: wg
          image: ubuntu:24.04
          command: ["sleep", "36000"]
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
            - name: hc
              containerPort: 9000
              protocol: TCP
          securityContext:
            # allowPrivilegeEscalation: false
            # runAsNonRoot: true
            capabilities:
              # drop: ["ALL"]
              add: ["NET_ADMIN"] # kernel WG + iptables/nft configuration
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Tell NLB how to check target health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    # Optional but useful to avoid IPv6 weirdness
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  selector:
    app: wireguard-proxy
  ports:
    - name: wg
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: hc
      port: 9000
      targetPort: 9000
      protocol: TCP
