apiVersion: v1
kind: Service
metadata:
  name: wireguard-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Tell NLB how to check target health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    # Optional but useful to avoid IPv6 weirdness
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0b4644cb4c7c3523f,subnet-052920c419ff1afe4,subnet-0424886b81989a5b3"
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  selector:
    app: wireguard-proxy
  ports:
    - name: wg
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: hc
      port: 9000
      targetPort: 9000
      protocol: TCP
