apiVersion: v1
kind: Service
metadata:
  name: wireguard-nodeport
  namespace: skarupa-exp
spec:
  type: NodePort
  externalTrafficPolicy: Cluster   # use "Local" if you need to preserve client IPs
  selector:
    app: wireguard-proxy
  ports:
    - name: wg
      protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 31820        # open this in the node SG (UDP)
    - name: nginx
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31821        # open this in the node SG (UDP)
