apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "chart.fullname" . }}-virtual-kubelet"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "chart.fullname" . }}-virtual-kubelet"
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.fullname" . }}
    namespace: {{ .Release.Namespace }}
