apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "chart.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "chart.fullname" . }}"
        gpu-provider-gateway: "true"
    spec:
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "chart.fullname" . }}"

      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}

      # Gateway WG secrets init
      initContainers:
        - name: gateway-init
          image: {{ .Values.deployment.containers.gateway.image.repository }}:{{ .Values.deployment.containers.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.gateway.image.pullPolicy }}
          command: ["/gateway-init"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
            {{- if .Values.deployment.gateway.domain }}
            - name: GATEWAY_ENDPOINT
              value: {{ .Values.deployment.gateway.domain }}
            {{- end }}
            - name: GATEWAY_SERVICE_NAME
              value: "{{ include "chart.fullname" . }}-gateway"
            - name: GATEWAY_PORT
              {{- if eq .Values.deployment.gateway.class "aws-eks" }}
              value: "51820"
              {{- else }}
              value: "{{ .Values.deployment.gateway.nodePort }}"
              {{- end }}
            - name: PEER_COUNT
              value: "32"
          volumeMounts:
            - name: gateway-config
              mountPath: /gateway

      containers:
        # Virtual Kubelet
        - name: virtual-kubelet
          image: {{ .Values.deployment.containers.virtualKubelet.image.repository }}:{{ .Values.deployment.containers.virtualKubelet.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.virtualKubelet.image.pullPolicy }}
          args:
            - --provider-config=/virtual-kubelet-config.yaml
          {{- if .Values.deployment.containers.virtualKubelet.resources }}
          resources:
            {{- toYaml .Values.deployment.containers.virtualKubelet.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BANS_OVERWRITE
              value: "{\"203531\":\"2026-01-08T06:30:36.205086888+01:00\"}"
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
            - name: PROXY_ENABLE
              value: "true"
            - name: VKUBELET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if and .Values.deployment.tls.cert .Values.deployment.tls.key .Values.deployment.tls.caCert }}
            - name: TLS_CERT_PATH
              value: "/etc/kubelet-tls/tls.crt"
            - name: TLS_KEY_PATH
              value: "/etc/kubelet-tls/tls.key"
            - name: TLS_CA_CERT_PATH
              value: "/etc/kubelet-tls/ca.crt"
            {{- end }}
          volumeMounts:
            - name: virtual-kubelet-config
              mountPath: /virtual-kubelet-config.yaml
              subPath: virtual-kubelet-config.yaml
              readOnly: true
            - name: gateway-config
              mountPath: /gateway
            {{- if and .Values.deployment.tls.cert .Values.deployment.tls.key .Values.deployment.tls.caCert }}
            - name: virtual-kubelet-tls
              mountPath: /etc/kubelet-tls
            {{- end }}

        # Gateway
        - name: gateway
          image: {{ .Values.deployment.containers.gateway.image.repository }}:{{ .Values.deployment.containers.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.gateway.image.pullPolicy }}
          env:
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
            - name: hc
              containerPort: 9000
              protocol: TCP
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          {{- if .Values.deployment.containers.gateway.resources }}
          resources:
            {{- toYaml .Values.deployment.containers.gateway.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gateway-config
              mountPath: /gateway

        # DNS Forwarder
        - name: wg-dns
          image: coredns/coredns:1.11.1
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: wg-dns-corefile
              mountPath: /etc/coredns
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

        # Gateway Controller
        - name: gateway-controller
          image: {{ .Values.deployment.containers.gateway.image.repository }}:{{ .Values.deployment.containers.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.gateway.image.pullPolicy }}
          command: ["/gateway-controller"]
          args:
            - --haproxy-socket=http://127.0.0.1:5555
            - --haproxy-username=admin
            - --haproxy-password=admin
            - --workers=2
            - -v=4
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.deployment.containers.gatewayController.resources }}
          resources:
            {{- toYaml .Values.deployment.containers.gatewayController.resources | nindent 12 }}
          {{- end }}

      volumes:
        - name: virtual-kubelet-config
          configMap:
            name: "{{ include "chart.fullname" . }}-virtual-kubelet-config"
        {{- if and .Values.deployment.tls.cert .Values.deployment.tls.key .Values.deployment.tls.caCert }}
        - name: virtual-kubelet-tls
          secret:
            secretName: "{{ include "chart.fullname" . }}-tls"
        {{- end }}
        - name: gateway-config
          emptyDir:
            sizeLimit: 500Mi
            medium: Memory
        - name: wg-dns-corefile
          configMap:
            name: "{{ include "chart.fullname" . }}-wg-dns-corefile"
