apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "chart.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "chart.fullname" . }}"
    spec:
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "chart.fullname" . }}"

      {{- if .Values.deployment.gateway.enable }}
      initContainers:
        - name: gateway-init
          image: {{ .Values.deployment.gateway.image.repository }}:{{ .Values.deployment.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.gateway.image.pullPolicy }}
          command: ["/gateway-init"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
            {{- if .Values.deployment.gateway.domain }}
            - name: GATEWAY_ENDPOINT
              value: {{ .Values.deployment.gateway.domain }}
            {{- end }}
            - name: GATEWAY_SERVICE_NAME
              value: "{{ include "chart.fullname" . }}-gateway"
            - name: GATEWAY_PORT
              value: "{{ .Values.deployment.gateway.port }}"
          volumeMounts:
            - name: gateway-config
              mountPath: /gateway
      {{- end }}

      containers:
        - name: virtual-kubelet
          image: {{ .Values.deployment.containers.virtualKubelet.image.repository }}:{{ .Values.deployment.containers.virtualKubelet.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.virtualKubelet.image.pullPolicy }}
          args:
            - --provider-config=/virtual-kubelet-config.yaml
          {{- if .Values.deployment.containers.virtualKubelet.resources }}
          resources:
            {{- toYaml .Values.deployment.containers.virtualKubelet.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.deployment.gateway.enable }}
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
            - name: PROXY_ENABLE
              value: "true"
            {{- end }}
            - name: VKUBELET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: virtual-kubelet-config
              mountPath: /virtual-kubelet-config.yaml
              subPath: virtual-kubelet-config.yaml
              readOnly: true
            {{- if .Values.deployment.gateway.enable }}
          volumeMounts:
            - name: gateway-config
              mountPath: /gateway
            {{- end }}

        {{- if .Values.deployment.gateway.enable }}
        - name: gateway
          image: {{ .Values.deployment.gateway.image.repository }}:{{ .Values.deployment.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.gateway.image.pullPolicy }}
          env:
            - name: GATEWAY_CONFIG_PATH
              value: "/gateway/config.yaml"
          ports:
            - name: wg
              containerPort: {{ .Values.deployment.gateway.port }}
              protocol: UDP
            - name: hc
              containerPort: 9000
              {{- if not .Values.deployment.gateway.AWSLoadBalancerController }}
              hostPort: {{ .Values.deployment.gateway.nodePort }}
              {{- end }}
              protocol: TCP
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          {{- if .Values.deployment.gateway.resources }}
          resources:
            {{- toYaml .Values.deployment.gateway.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gateway-config
              mountPath: /gateway
        {{- end }}

        - name: wg-dns
          image: coredns/coredns:1.11.1
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: wg-dns-corefile
              mountPath: /etc/coredns
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

      volumes:
        - name: virtual-kubelet-config
          configMap:
            name: "{{ include "chart.fullname" . }}-virtual-kubelet-config"
        {{- if .Values.deployment.gateway.enable }}
        - name: gateway-config
          emptyDir:
            sizeLimit: 500Mi
            medium: Memory
        - name: wg-dns-corefile
          configMap:
            name: wg-dns-corefile
        {{- end }}
{{/*            secretName: "{{ include "chart.fullname" . }}-gateway-config"*/}}
