{{- if .Values.appConfig.gateway.config }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-gateway-config"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.appConfig.gateway.config | toYaml | nindent 4 }}
{{- end }}
