{{- if eq .Values.deployment.gateway.class "aws-eks" }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-gateway"
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
    {{- if .Values.deployment.gateway.domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.deployment.gateway.domain }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  selector:
    app: "{{ include "chart.fullname" . }}"
  ports:
    - name: wg
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: hc
      port: 9000
      targetPort: 9000
      protocol: TCP
{{- else if eq .Values.deployment.gateway.class "node-port" }}

{{- $d := default "" .Values.deployment.gateway.domain | trim -}}
{{- if eq $d "" -}}
  {{- fail "deployment.gateway.domain is required when deployment.gateway.class is node-port" -}}
{{- end -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-gateway"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ include "chart.fullname" . }}"
  ports:
    - port: 51820
      targetPort: 51820
      nodePort: {{ .Values.deployment.gateway.nodePort }}
      protocol: UDP
{{- end }}
