apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-gateway"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "chart.fullname" . }}-gateway"
  template:
    metadata:
      labels:
        app: "{{ include "chart.fullname" . }}-gateway"
    spec:
      containers:
        - name: virtual-kubelet
          image: {{ .Values.deployment.gateway.image.repository }}:{{ .Values.deployment.gateway.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.gateway.image.pullPolicy }}
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
            - name: hc
              containerPort: 9000
              {{- if not .Values.deployment.gateway.AWSLoadBalancerController }}
              hostPort: {{ .Values.deployment.gateway.nodePort }}
              {{- end }}
              protocol: TCP
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          {{- if .Values.deployment.gateway.resources }}
          resources:
            {{- toYaml .Values.deployment.gateway.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/wireguard/proxy.yaml
              subPath: proxy-config.yaml
              readOnly: true
      volumes:
        - name: proxy-config
          secret:
            secretName: {{ required "Values.deployment.gateway.wgSecretName must be on-empty. Deploy pre-generated Wireguard keys as a secret and reference its name here" .Values.deployment.gateway.wgSecretName }}
      serviceAccountName: "{{ include "chart.fullname" . }}"
