apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-tls"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.deployment.tls.cert }}
  tls.key: {{ .Values.deployment.tls.key }}
  ca.crt: {{ .Values.deployment.tls.caCert }}
