apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "chart.fullname" . }}-virtual-kubelet-config"
data:
  virtual-kubelet-config.yaml: |
    logLevel: {{ .Values.appConfig.logLevel | quote }}
    cluster:
      clusterUUID: {{ .Values.appConfig.cluster.clusterUUID | quote }}
    cloudProvider:
      vastAI:
        apiKey: {{ .Values.appConfig.cloudProvider.vastAI.apiKey | quote }}
    provisioning:
      maxRetries: {{ .Values.appConfig.provisioning.maxRetries }}
      startupTimeout: {{ .Values.appConfig.provisioning.startupTimeout }}
      machineBansStore:
        localFile:
          enable: {{ .Values.appConfig.provisioning.machineBansStore.localFile.enable }}
          {{- if .Values.appConfig.provisioning.machineBansStore.localFile.timeout }}
          timeout: {{ .Values.appConfig.provisioning.machineBansStore.localFile.timeout | quote }}
          {{- end }}
    virtualNode:
      nodeName: {{ .Values.appConfig.virtualNode.nodeName | quote }}
      pods: {{ .Values.appConfig.virtualNode.podLimit | quote }}
      cpu: {{ .Values.appConfig.virtualNode.cpu | quote }}
      memory: {{ .Values.appConfig.virtualNode.memory | quote }}
      {{- if .Values.appConfig.virtualNode.labels }}
      labels:
        {{- toYaml .Values.appConfig.virtualNode.labels | nindent 8 }}
      {{- else }}
      labels: {}
      {{- end }}
      {{- if .Values.appConfig.virtualNode.taints }}
      taints:
        {{- toYaml .Values.appConfig.virtualNode.taints | nindent 8 }}
      {{- else }}
      taints: []
      {{- end }}
    proxy:
      enable: {{ .Values.appConfig.proxy.enable }}
      {{- if .Values.appConfig.proxy.configPath }}
      configPath: {{ .Values.appConfig.proxy.configPath | quote }}
      {{- end }}
    {{- if .Values.appConfig.agentAuthToken }}
    agentAuthToken: {{ .Values.appConfig.agentAuthToken | quote }}
    {{- end }}
    promtail:
      enable: {{ .Values.appConfig.promtail.enable }}
      {{- if .Values.appConfig.promtail.clients }}
      clients:
        {{- toYaml .Values.appConfig.promtail.clients | nindent 8 }}
      {{- else }}
      clients: []
      {{- end }}
