apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-virtual-kubelet"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "chart.fullname" . }}-virtual-kubelet"
  template:
    metadata:
      labels:
        app: "{{ include "chart.fullname" . }}-virtual-kubelet"
    spec:
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: virtual-kubelet
          image: {{ .Values.deployment.containers.virtualKubelet.image.repository }}:{{ .Values.deployment.containers.virtualKubelet.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.containers.virtualKubelet.image.pullPolicy }}
          # command: ['sleep', '3600']
          args:
            - --provider-config=/virtual-kubelet-config.yaml
          {{- if .Values.deployment.containers.virtualKubelet.resources }}
          resources:
            {{- toYaml .Values.deployment.containers.virtualKubelet.resources | nindent 12 }}
          {{- end }}
          env:
            - name: VIRTUAL_NODE_PODS
              value: "100"
            {{- if .Values.deployment.gateway.enable }}
            - name: PROXY_CONFIG_PATH
              value: "/proxy-config.yaml"
            {{- end }}
            {{- if .Values.deployment.gateway.enable }}
            - name: PROXY_ENABLE
              value: "true"
            {{- end }}
            - name: VKUBELET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BANS_OVERWRITE
              value: '{"23779":"2025-11-04T10:45:36.205086888+01:00","34425":"2025-11-04T10:45:36.205086888+01:00"}'
          volumeMounts:
            - name: vk-config
              mountPath: /virtual-kubelet-config.yaml
              subPath: virtual-kubelet-config.yaml
              readOnly: true
          {{- if .Values.deployment.gateway.enable }}
            - name: proxy-config
              mountPath: /proxy-config.yaml
              subPath: proxy-config.yaml
              readOnly: true
          {{- end }}
      volumes:
        - name: vk-config
          configMap:
            name: "{{ include "chart.fullname" . }}-virtual-kubelet-config"
        {{- if .Values.deployment.gateway.enable }}
        - name: proxy-config
          secret:
            secretName: {{ .Values.deployment.gateway.wgSecretName }}
        {{- end }}
      serviceAccountName: "{{ include "chart.fullname" . }}"
