apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "chart.fullname" . }}-wg-dns-corefile"
data:
  Corefile: |
    .:53 {
      errors
      log
      cache 30
      forward . 10.100.0.10
    }
